CREATE TABLE "LoopRun" (
    "id" VARCHAR,
    "title" VARCHAR,
    "timestamp" VARCHAR,
    "status" VARCHAR,
    "run_spec" VARCHAR,
    "run_spec_version" VARCHAR,
    "run_spec_digest" VARCHAR,
    "run_spec_snapshot" VARCHAR,
    "session_type" VARCHAR,
    "task" VARCHAR,
    "resumed_handoff" VARCHAR,
    "readings" VARCHAR[],
    "goals" VARCHAR[],
    "decisions" VARCHAR[],
    "evidence" VARCHAR[],
    "checks" VARCHAR[],
    "outcome" VARCHAR,
    "skills_consulted" VARCHAR[],
    "experiences_recorded" VARCHAR[],
    "proposals_generated" VARCHAR[]
);
